ezsystems/EzSystemsRecommendationBundle

eZ/Publish/LegacySearch/LegacySearchFactory.php, eZ/Publish/LegacySearch/NullSearchEngine.php, eZ/Publish/LegacySearch/RecommendationLegacySearchEngine.php
Link to Jira task: https://jira.ez.no/browse/EZP-23860
=> EZP-23860: RecommendationBundle breaks left tree menu

Client/YooChooseNotifier.php, Resources/config/services.yml
Link to Jira task: https://jira.ez.no/browse/EZP-24560
=> EZP-24560: Add ContentTypeId when notification event is submitted to YC

Client/YooChooseNotifier.php
Link to Jira task: https://jira.ez.no/browse/EZP-24559
`$this->guzzle->setDefaultOption()` is deprecated since v5 of Guzzle.
=> EZP-24559: Problem notifying YC about content update

Resources/public/js/recommendationrestclient.js, Resources/public/js/recommendationtemplatehelper.js, Resources/public/js/recommendationtemplaterenderer.js, Resources/public/views/show_recommendations.html.twig, composer.json
Link to Jira task: https://jira.ez.no/browse/EZP-24594
=> EZP-24594: code improvement and cleanup

Resources/public/js/recommendationrestclient.js, Resources/public/views/show_recommendations.html.twig, Twig/RecommendationTwigExtension.php
Link to Jira task: https://jira.ez.no/browse/EZP-24659
Waiting for YC API to update - do not merge it yet!
=> EZP-24659: Replace `outputtype` parameter with `outputtypeid` in request query string

Resources/config/services.yml, Twig/RecommendationTwigExtension.php
Link to Jira task: https://jira.ez.no/browse/EZP-24674
=> EZP-24674: Fix siteaccess aware configuration issues

Resources/public/js/recommendationrestclient.js, Resources/public/views/show_recommendations.html.twig, Twig/RecommendationTwigExtension.php
Reverts ezsystems/EzSystemsRecommendationBundle#17
=> Revert "EZP-24659: Replace `outputtype` parameter with `outputtypeid`

Resources/config/default_settings.yml
Link to Jira task: https://jira.ez.no/browse/EZP-24682
=> EZP-24682: Add example settings for `default` scope in `default_settings.yml` configuration

Resources/public/js/recommendationrestclient.js, Resources/public/views/show_recommendations.html.twig
Link to Jira task: https://jira.ez.no/browse/EZP-24679
=> EZP-24679: Improve error handling

README.md, Resources/config/default_settings.yml
Link to Jira task: https://jira.ez.no/browse/EZP-24680
=> EZP-24680: Change default value for ez_recommendation.recommender.api_endpoint

Client/YooChooseNotifier.php, Resources/config/services.yml
Link to Jira task: https://jira.ez.no/browse/EZP-24681
=> EZP-24681: Defining that SignalSlots are invoked only for relevant content types

README.md, Rest/Controller/ContentController.php
Fixed author field, now shows string.
Ping @lserwatka
=> proper value for author field

Rest/Controller/ContentController.php
Changes after multiple image issue (controller returned image for every field if there were no images in request and related content was found)
Solution was to check if related field exists for specified value, not for content, then check it's value.
ping @andrerom @lserwatka @michalpipa
=> Fixed multiple images issue with related content

Rest/ValueObjectVisitor/ContentData.php
=> Header Content-Type set

README.md, Resources/config/services.yml, Rest/Controller/ContentController.php, Rest/Field/TypeValue.php, Rest/Field/Value.php
Created helper for parsing field value (e.g. _ezxmltext_ has to be **HTML** insted of **XML**)
=> Created helpers for parsing field values

Rest/Controller/ContentController.php, Rest/Controller/ContentTypeController.php
https://jira.ez.no/browse/EZS-212
Custom controller behaviour based on __path__ and __hidden__ parameters
=> Path and hidden query parameters

Rest/Controller/ContentController.php, Rest/Controller/ContentTypeController.php
Without it, recommendation bundle wont work on latest ezpublish-kernel
=> Fix: use Request via injection as setter was dropped few weeks ago

EventListener/Login.php, Twig/RecommendationTwigExtension.php
PR done because of discussion made in comments to https://github.com/ezsystems/EzSystemsRecommendationBundle/pull/35#discussion-diff-40291506
=> Added double pipes in conditions when checking user authentication

EventListener/Login.php, Resources/config/services.yml, Twig/RecommendationTwigExtension.php
Link to Jira task: https://jira.ez.no/browse/EZS-320
*This PR is related to https://github.com/ezsystems/EzSystemsRecommendationBundle/pull/35 and https://github.com/ezsystems/EzSystemsRecommendationBundle/pull/48*
=> EZS-320: Fix a fatal error when the token comes from an external provider

README.md, Tests/Client/YooChooseNotifierTest.php, Tests/bootstrap.php
Link to Jira task: https://jira.ez.no/browse/EZS-323
This PR is related to https://github.com/ezsystems/EzSystemsRecommendationBundle/pull/49
=> EZS-323: Fix and update broken notification tests

Client/YooChooseNotifier.php
Method name was misleading. Fixed to avoid mistakes.
=> Rename getContentIdentifier() method name to getContentTypeIdentifier()

Client/YooChooseNotifier.php
Link to Jira task: https://jira.ez.no/browse/EZP-25904
=> Fix EZP-25904: Prevent crash when discarding draft

Resources/config/services.yml, Rest/Field/TypeValue.php, composer.json
Changed converter from xml to richtext
JIRA: https://jira.ez.no/browse/EZS-416
=> EZS-416 EzRecommendationBundle doesn't work with EzPlatform

Client/YooChooseNotifier.php, Resources/config/services.yml, Tests/Client/YooChooseNotifierTest.php
Link to Jira task: https://jira.ez.no/browse/EZP-25898
Improved solution originally proposed in https://github.com/ezsystems/EzSystemsRecommendationBundle/pull/59
=> EZP-25898: Prevent crash when updating non-public content item

.travis.yml, Client/YooChooseNotifier.php, Tests/Client/YooChooseNotifierTest.php, composer.json
Improved version of #64 with passing tests.
=> Updated Guzzle dependencies to work with eZ Publish >= 5.4.6

EventListener/SessionBackup.php
JIRA: https://jira.ez.no/browse/EZS-822
=> EZS-822 Cannot log in into ezstudio demo installation

eZ/Publish/LegacySearch/RecommendationLegacySearchEngine.php
JIRA: https://jira.ez.no/browse/EZS-821
=> Fix EZS-821: Proxy all legacy search events to real legacy search engine

Resources/views/show_recommendations.html.twig
Argument names are incorrect according to https://github.com/ezsystems/EzSystemsRecommendationBundle/blob/master/Resources/public/js/recommendationrestclient.js#L26-L27
=> Fixed argument names for RecommendationRestClient

Resources/config/services.yml, Rest/Controller/ContentController.php, Rest/Controller/ContentTypeController.php
JIRA: https://jira.ez.no/browse/EZS-789
Added new query parameter `sa` which reffers to siteAccess. Sample usage:
`sa=de`:
```
/api/ezp/v2/ez_recommendation/v1/contenttypes/16,18,38?hidden=1&fields=title,name&page_size=50&sa=de
```
=> EZS-789 Multisite support in Personalization

Rest/Controller/ContentTypeController.php, Rest/Response/ExportResponse.php
=> YC response additional info.

Twig/RecommendationTwigExtension.php
ping @lserwatka @clash82 @damianz5
=> Changed methods access. Allow to extend Twig Extension in other bundles.

Resources/config/services.yml, Rest/Controller/ContentController.php, Rest/Controller/ContentTypeController.php, Rest/Response/ExportResponse.php, Rest/Response/HttpResponse.php
EZS-1130 Content export to file - add webHook flexibility.
JIRA: https://jira.ez.no/browse/EZS-1128 https://jira.ez.no/browse/EZS-1130
=> EZS-1128 Items export for YOOCHOOSE - wrong header.

Client/RecommendationClient.php, Client/YooChooseNotifier.php, Resources/config/services.yml, Rest/Field/TypeValue.php, eZ/Publish/Slot/HideLocation.php, eZ/Publish/Slot/UnhideLocation.php
JIRA: https://jira.ez.no/browse/EZP-27149
=> EZP-27149 Reproduce and fix AMNH invalidate/hide notifications.

Rest/Controller/ContentController.php
JIRA: https://jira.ez.no/browse/EZP-27150 https://jira.ez.no/browse/CS-6074
=> EZP-27150 Content fetching ERROR.

.php_cs, Client/YooChooseNotifier.php, EventListener/Login.php, LICENSE, Rest/Controller/ExportController.php, composer.json
**JIRA: https://jira.ez.no/browse/EZEE-1446**
Also fixed our codebase according to the new configuration.
Note: Merge upwards to master branch
=> EZEE-1446: Fix .php_cs config in EZEE repositories

Client/YooChooseNotifier.php, Resources/config/services.yml, Rest/Field/TypeValue.php, eZ/Publish/LegacySearch/RecommendationLegacySearchEngine.php
Added hide and show call. Guzzle promise execution.
JIRA: https://jira.ez.no/browse/EZP-27150
=> Fixes after legacy tests

README.md
https://jira.ez.no/browse/EZP-27044
This mostly copies changes made previously to the Confluence doc that had not been applied here.
Also, some proofing and a clearer structure of README.
=> EZP-27044 - Align README with doc on Confluence

EventListener/Login.php, EventListener/SessionBackup.php, Resources/config/services.yml, Twig/RecommendationTwigExtension.php
EZEE-1615 Login event has to be sent (it is sent after a succesful login).
JIRA: 
https://jira.ez.no/browse/EZEE-1614
https://jira.ez.no/browse/EZEE-1615
=> EZEE-1614 Replace tracked userId.

EventListener/Login.php, Resources/config/services.yml, Resources/public/js/recommendationrestclient.js, Resources/public/js/recommendationtemplaterenderer.js, Resources/views/default.html.twig, Twig/RecommendationTwigExtension.php
JIRA: https://jira.ez.no/browse/EZEE-1619
=> EZEE-1619 Switch to api v2 calls: (PROD system)

Resources/config/services.yml
FIt `services.yml` to Symfony strict yaml parser.
=> YAML quotations.

.travis.yml, Client/YooChooseNotifier.php, Tests/Client/YooChooseNotifierTest.php
fix for tests and logger
https://jira.ez.no/browse/EZEE-1718
=> EZEE-1718: fix for tests and logger

Resources/config/default_settings.yml
Unable to publish content with default ez recommendation config
https://jira.ez.no/browse/EZEE-1741
=> EZEE-1741: Unable to publish content with default ezreco config

EventListener/Login.php, Resources/config/services.yml, Twig/RecommendationTwigExtension.php
https://jira.ez.no/browse/EZEE-1782
=> EZEE-1782: support for multiple user providers

composer.json
Required changes for EzPlatform v2
=> changes for EzPlatform v2

Client/YooChooseNotifier.php
https://jira.ez.no/browse/EZP-28793
=> EZP-28793: Delete draft button does not redirect to content view
