ezsystems/EzSystemsRecommendationBundle

- Rest/Field/Value.php
Related JIRA ticket: https://jira.ez.no/browse/EZP-24779
It may happen if database data is corrupted for unknown reason (possibly failed import from 3rd party system or human factor).
This simple fix prevents asking for related object with NULLed contentId.
Internal Server Error ```Invalid or Empty Node passed to getItem constructor.``` fixed. Now, on dev enviroment we get another error, yet I'm unsure if it's due to still corrupted data or just because image file is missing on dev enviroment:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ErrorMessage media-type="application/vnd.ez.api.ErrorMessage+xml">
<errorCode>406</errorCode>
<errorMessage>Not Acceptable</errorMessage>
<errorDescription>Argument 'BinaryFile::id' is invalid: …
```
> (WIP) EZP-24779 fix: prevent error if image is related to non-existing object

- Rest/Field/Value.php
We shouldn't remove original field identifier name from related object. It's misleading for end users, as they ask for ie. "image" and can get any identifier in result.
> fix: leave original field identifier for related field

- Rest/Controller/ContentController.php
As default language we take content type language and not language of actual content object. It results in empty values if content is in different language from its content type language.
> fix: change default content language to object lang instead of type lang

- README.md
- Resources/config/services.yml
It should be enable on demand, not by default.
> fix: disable legacy search engine dependency by default

- Exception/InvalidRelationException.php
- Resources/config/default_settings.yml
- Resources/config/services.yml
- Rest/Field/RelationMapper.php
- Rest/Field/Value.php
Previously if related content had two or more matching fields we picked the last one, regardless if it's correct one or not. Now, by configuration, customer is able to point `content.field` to another `content.field`.
Example configuration (`parameters.yml`):
```yaml
parameters:
ez_recommendation.relations:
article.image: image.image_thumb
cat.photo: gallery.main_image
```
> fix: configurable mapping should be more precise

- Resources/config/services.yml
- Rest/Field/Value.php
In result it will log a descriptive information about wrong relation and return empty field value instead of `Internal Server Error`
Log example: `[2015-10-01 15:34:18] app.WARNING: Invalid relation: field 'blog_post:image' (object: 73784, field: 1382616) has improper relation to object 'folder' (object: 62315); 'image:image' expected. [] []`
> fix: log wrong relation and return empty value instead of uncaught exception

- Rest/Field/TypeValue.php
Right now we do not catch `SourceImageNotFoundException` so it may result in `500 Internal Server Error` in case of missing binary file.
**Note**: This does not fix `Argument 'BinaryFile::id' is invalid` error (different origin).
> fix: return empty value if source binary file is missing

- README.md
*Side: Don't really see the need to duplicate this on confluence, so better if doc team can contribute fixes to the install doc here imho. Tried to look for relevant changes in confluence page that should be applied here, last chapter I wrote with different links as the pages suggested on confluence where as far as I can see irrelevant for users *(out of date/regarding old extension, api and developer guide by yoochoose seemed more relevant to read after you have installed bundle).*
> Update README.md to prepare for release

- .travis.yml
- Client/YooChooseNotifier.php
- Tests/Client/YooChooseNotifierTest.php
- composer.json
Issue: https://jira.ez.no/browse/EZP-26034
Adapts code to support both Guzzle5 and Guzzle6 at the same time, and re enable PHP 5.4 testing.
While on it, also take advantage of asynchronous http support in Guzzle 6.
Once passed, reviewed  and merged we'll need a `v1.0.2-rc1` tag for ongoing eZ Publish 5.4.7 QA.
review ping @lserwatka @clash82
> EZP-26034: Re add guzzle5 & PHP 5.4 support

- Client/YooChooseNotifier.php
- README.md
- Resources/config/routing_rest.yml
- Resources/config/services.yml
- Resources/config/slots.yml
- Resources/views/default.html.twig
- composer.json
- phpunit.xml
This PR Resolves [EZP-26128](https://jira.ez.no/browse/EZP-26128) for this repository.
It also allows us to move forward with Symfony `3.0` integration in the future (mentioned in #72 and related to [Kernel PR #1753](https://github.com/ezsystems/ezpublish-kernel/pull/1753)).
**TODO**:
> EZP-26128: As a Developer I want deprecation issues resolved, so that application logs are clean

- DependencyInjection/Compiler/RestResponsePass.php
- EzSystemsRecommendationBundle.php
- Resources/config/routing_rest.yml
- Resources/config/services.yml
- Rest/Controller/ContentController.php
- Rest/Controller/ContentTypeController.php
- Rest/Controller/ExportController.php
- Rest/Exception/ExportInProgressException.php
- Rest/Exception/ResponseClassNotImplementedException.php
- Rest/Exception/UnsupportedResponseTypeException.php
- Rest/Field/RelationMapper.php
- Rest/Response/ExportResponse.php
- Rest/Response/HttpResponse.php
- Rest/Response/Response.php
- Rest/Response/ResponseInterface.php
- Rest/ValueObjectVisitor/ContentData.php
- Rest/ValueObjectVisitor/ContentListElementGenerator.php
- Rest/Values/ContentData.php
JIRA: https://jira.ez.no/browse/EZS-911
Add `/export` after content type list in url for export to files, eg.:
`/api/ezp/v2/ez_recommendation/v1/contenttypes/18,16/export?fields=title,image`
Default page size is set to:
* 10 for regular response
* 1000 for export response
It can be changed by setting `page_size`: `[...]&page_size=120`
`page (offset)` argument is ignored in `export` response
Export finish trigger the POST request to Yoochoose endpoint `/api/{customerId}/items` sending a list of urls for downloading the content files and credentials necessary for authorization. That request is also a response displayed after export finish.
> EZS-911 Initial bulk upload of content to Personalization Service

- Resources/public/js/recommendationrestclient.js
- Resources/views/default.html.twig
- Resources/views/show_recommendations.html.twig
- Twig/RecommendationTwigExtension.php
Added custom filters (as part of params array).
Usage:
```
{{ yc_show_recommendations(
contentId = content.id,
scenario = 'article',
limit = '3',
contentType = 'article',
template = 'recommendations',
fields = ['title', 'intro', 'image', 'url'],
params = {
'filters': {
tags: 'tag1,tag2',
type: '2'
}
}
) }}
```
JIRA: 
* https://jira.ez.no/browse/CS-6130
* https://jira.ez.no/browse/EZEE-1382
> EZEE-1382 Add custom filters to a request to eZ Recommendation

- .php_cs
- .travis.yml
- Tests/Client/YooChooseNotifierTest.php
- composer.json
This PR updates `.php_cs` config and adds composer command `fix-cs`:
```
composer fix-cs
```
to simplify fixing CS.
**TODO**:
> EZP-28161: Update php-cs-fixer configuration to align with v2.7.1

- Client/RecommendationClient.php
- Client/YooChooseNotifier.php
- Tests/Client/YooChooseNotifierTest.php
- eZ/Publish/Slot/CopyContent.php
- eZ/Publish/Slot/DeleteVersion.php
- eZ/Publish/Slot/PublishVersion.php
Notifier cleanup for export feature (will be added as separate PR)
Changes have been extracted from https://github.com/ezsystems/EzSystemsRecommendationBundle/pull/94
https://jira.ez.no/browse/EZEE-1272
https://jira.ez.no/browse/EZEE-1785
> Notifier cleanup

- Resources/config/slots.yml
- Tests/eZ/Publish/Slot/AbstractPersistenceAwareBaseTest.php
- Tests/eZ/Publish/Slot/AbstractSlotTest.php
- Tests/eZ/Publish/Slot/CopyContentTest.php
- Tests/eZ/Publish/Slot/CopySubtreeTest.php
- Tests/eZ/Publish/Slot/CreateLocationTest.php
- Tests/eZ/Publish/Slot/DeleteContentTest.php
- Tests/eZ/Publish/Slot/DeleteLocationTest.php
- Tests/eZ/Publish/Slot/DeleteVersionTest.php
- Tests/eZ/Publish/Slot/HideLocationTest.php
- Tests/eZ/Publish/Slot/MoveSubtreeTest.php
- Tests/eZ/Publish/Slot/PublishVersionTest.php
- Tests/eZ/Publish/Slot/RecoverTest.php
- Tests/eZ/Publish/Slot/SetContentStateTest.php
- Tests/eZ/Publish/Slot/TrashTest.php
- composer.json
- eZ/Publish/Slot/PublishVersion.php
- eZ/Publish/Slot/Recover.php
- eZ/Publish/Slot/Trash.php
> JIRA: https://jira.ez.no/browse/EZEE-1784
This PR adds a missing synchronization of (reverse) related objects, which should be done together with Content Object after its modification.
> EZEE-1784: Update reverse relations when content object is published

- EventListener/SessionBackup.php
JIRA ticket: [EZEE-1889](https://jira.ez.no/browse/EZEE-1889)
Excerpt from the ticket:
> There have been reports of the following errors in the error log coming from the Recommendation Bundle (SessionBackup listener):
`PHP Fatal error: Uncaught exception 'Symfony\\Component\\Debug\\Exception
FatalErrorException' with message 'Error: Call to a member function isStarted() on null' in /xxx/vendor/ezsystems/recommendation-bundle/EventListener/SessionBackup.php:28\nStack trace:\n#0`
It seems that in some circumstances `$request->getSession()` might return null, which causes the issue above.
> EZEE-1889: SessionBackup Listener returns error when Session object doesn't exist

- Resources/config/services.yml
JIRA issue: https://jira.ez.no/browse/EZEE-2169
The issue comes from the usage of deprecated and removed in Symfony 3.0 `factory_class` and `factory_method` DI methods. Ref:
https://api.symfony.com/2.7/Symfony/Component/DependencyInjection/Definition.html#method_setFactoryClass
https://api.symfony.com/2.7/Symfony/Component/DependencyInjection/Definition.html#method_setFactoryMethod
Documentation PR: https://github.com/ezsystems/developer-documentation/pull/324
> EZEE-2196: [LegacyBridge] Cannot instantiate interface ezpSearchEngine error

- Resources/config/services.yml
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZEE-2256](https://jira.ez.no/browse/EZEE-2256)
| **Bug**| yes
| **New feature**    | no
> EZEE-2256: [LegacyBridge][eZ Recommendation][WebProfiler] Null is passed to PreBuildKernelWebHandlerEvent instead of valid Request object

- Resources/config/services.yml
This PR is a followup for https://github.com/ezsystems/EzSystemsRecommendationBundle/pull/113, where incorrect service has been set as `lazy` what was causing an exception when legacy backoffice (shipped with LegacyBridge) was in use.
> EZEE-2256: Set proper service as lazy

- Rest/Field/TypeValue.php
This PR solves an issue which causes the following error. `TypeValue` had a dependency on `ImageHandler` implementation which has been changed to `PlaceholderAliasGenerator` recently.
> {"ErrorMessage":{"_media-type":"application\/vnd.ez.api.ErrorMessage+json","errorCode":500,"errorMessage":"Internal Server Error","errorDescription":"Type error: Argument 2 passed to EzSystems\\RecommendationBundle\\Rest\\Field\\TypeValue::__construct() must be an instance of eZ\\Bundle\\EzPublishCoreBundle\\Imagine\\AliasGenerator, instance of eZ\\Bundle\\EzPublishCoreBundle\\Imagine\\PlaceholderAliasGenerator given, called in \/var\/www\/ezplatform-ee\/var\/cache\/prod\/ContainerUeyuunf\/getEzRecommendation_Rest_Field_TypeValueService.php on line 8"}}
Since it's a bug and even eZ Platform v2.2 still …
> TypeValue should has dependency to VariationHandler interface, not implementation

- .travis.yml
- Tests/eZ/Publish/Slot/AbstractPersistenceAwareBaseTest.php
- Tests/eZ/Publish/Slot/AbstractSlotTest.php
- Tests/eZ/Publish/Slot/CopySubtreeTest.php
- Tests/eZ/Publish/Slot/MoveSubtreeTest.php
- Tests/eZ/Publish/Slot/PublishVersionTest.php
- Tests/eZ/Publish/Slot/RecoverTest.php
- Tests/eZ/Publish/Slot/TrashTest.php
- composer.json
This PR removes old, unnecessary builds for PHP 5.4 & 5.5. 
Builds both for PHP 5.4 & PHP 5.5 tried to run tests using `ezsystems/ezpublish-kernel` 5.2.0.
Added builds for PHP 7.1 and PHP 7.2 instead. 
This PR is targeted to `2.2` since I want to unblock in my second PR (https://github.com/ezsystems/EzSystemsRecommendationBundle/pull/116), but target branch can be easily changed to master.
You can see example previous failing build here: https://travis-ci.org/ezsystems/EzSystemsRecommendationBundle/builds/425723882
@andrerom / @damianz5 can we drop support for kernel 5.x for `2.2` and up? It will be harder and harder to maintain the bundle which has to support such a wide range of eZ Publish / Platform versions.
> Removed unnecessary Travis builds

- EventListener/Login.php
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZEE-2313](https://jira.ez.no/browse/EZEE-2313)
| **Bug**| yes
| **New feature**    | no
This PR introduces additional session `isStarted` check which is necessary in case of using Symfony AuthenticationGuard(s).
> EZEE-2313: [eZ Reco] Session ID is empty when Symfony AuthenticationGuard is used

- Client/YooChooseNotifier.php
Usage of `eZ\Publish\Core\SignalSlot\Repository` instead of implemented interface prevents from decorating `ezpublish.api.repository` service in any system where Recommendation Bundle  is enabled
> Use Repository Interface instead of SignalSlot\Repository

- Tests/eZ/Publish/Slot/AbstractSlotTest.php
This PR removes usage of `PHPUnit5CompatTrait` since it is no longer available due to the kernel changes: https://github.com/ezsystems/ezpublish-kernel/pull/2446.
> Removed PHPUnit5CompatTrait usage from tests
